openapi: 3.0.0
info:
  title: Nische Store API
  description: Documentaci칩n de la API de Nische Store - M칩dulo de Usuarios
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Desarrollo
paths:
  /api/chat:
    get:
      summary: Acceder a la p치gina de chat
      description: Esta ruta se utiliza para acceder a la p치gina de chat. El usuario debe estar autenticado y no ser un administrador para acceder.
      tags:
        - Chat
      responses:
        '200':
          description: Los mensajes de chat fueron devueltos de forma exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChatMessage'

components:
  schemas:
    ChatMessage:
      type: object
      properties:
        username:
          type: string
          description: Nombre de usuario del remitente del mensaje.
        message:
          type: string
          description: Contenido del mensaje.
